 [Log]
Level = 'debug'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '1337'
LinkContractAddress = '0x663F3ad617193148711d28f5334eE4Ed07016602'

[[EVM.Nodes]]
Name = 'test'
WSURL = 'ws://3.12.151.33:8546'
HTTPURL = 'http://3.12.151.33:8545/'


[[EVM]]
ChainID = '1338'
LinkContractAddress = '0x663F3ad617193148711d28f5334eE4Ed07016602'

[[EVM.Nodes]]
Name = 'test2'
WSURL = 'ws://13.58.232.153:8546'
HTTPURL = 'http://13.58.232.153:8545/'


