[Log]
Level = 'debug'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '1337'
LinkContractAddress = '0x663F3ad617193148711d28f5334eE4Ed07016602'

[[EVM.Nodes]]
Name = 'test'
WSURL = 'ws://13.203.78.29:8546/'
HTTPURL = 'http://13.203.78.29:8545/'


[[EVM]]
ChainID = '1338'
LinkContractAddress = '0xA3C7c756fFF8cBD7d6CCbDFC696bC9cA7c58a3a0'

[[EVM.Nodes]]
Name = 'test2'
WSURL = 'ws://13.126.115.98:8546'
HTTPURL = 'http://13.126.115.98:8545/'