[Log]
Level = 'debug'  # More verbose logging for development

[WebServer]
AllowOrigins = '*'
SecureCookies = false
ListenIP = "0.0.0.0"

[WebServer.TLS]
HTTPSPort = 0

# First EVM Chain Configuration
[[EVM]]
ChainID = '1337'
[[EVM.Nodes]]
Name = 'LocalChain1'
WSURL = 'ws://35.154.214.75:8546'
HTTPURL = 'http://35.154.214.75:8545/'

# Second EVM Chain Configuration
[[EVM]]
ChainID = '1336'
[[EVM.Nodes]]
Name = 'LocalChain2'
WSURL = 'ws://13.233.122.217:8546'
HTTPURL = 'http://13.233.122.217:8545'