type = "directrequest"
schemaVersion = 1
name = "Message Sender"
contractAddress     = ""

observationSource   = """
    decode_log [type="ethabidecodelog"
                abi="MessageSent(bytes32 messageId, uint64 destinationChainSelector, address receiver, string text, address feeToken, uint256 fees, address sender)"
                data="$(jobRun.logData)"
                topics="$(jobRun.logTopics)"]

    send_tx    [type="ethtx" to="$(decode_log.receiver)" data="$(ethabiencode)" 
                abi="receiveMessage(string)"
                args=["$(decode_log.text)"]]

    decode_log -> send_tx
"""
