type = "directrequest"
schemaVersion = 1
name = "Cross-Chain Message Job v5"
externalJobID = "59e17a8f-14d1-4287-8cce-726bafbe5e03"
forwardingAllowed = false
maxTaskDuration = "0s"
contractAddress = "0x2E983A1Ba5e8b38AAAeC4B440B9dDcFBf72E15d1"
evmChainID = "1337"
minIncomingConfirmations = 0
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]

    fetch_data   [type="http"
                  method="POST"
                  url="http://host.docker.internal:8000/receive"
                  requestData="{\\"ChainID\\": $(decode_cbor.destChainId), \\"Message\\": $(decode_cbor.message)}"
                  headers="[\\"Authorization\\", \\"Bearer gS+xc4XUsv3CA+iURw0b3H8gEit0VDlk\\"]"
                  allowUnrestrictedNetworkAccess="true"]

    // Submit transaction back to the contract
    encode_data    [type="ethabiencode"
              abi="(bytes32 requestId, bytes32 messageId, bool confirmed)"
              data="{\\"requestId\\": $(decode_log.requestId), \\"messageId\\": $(decode_cbor.messageID), \\"confirmed\\": true}"]

    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{ \\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data) }"]

    submit_tx    [type="ethtx" to="0x2E983A1Ba5e8b38AAAeC4B440B9dDcFBf72E15d1" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch_data -> encode_data -> encode_tx -> submit_tx
"""